endpoints:
  - name: catbox
    group: host
    url: "https://catbox.moe"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
  - name: singapore
    group: proxy server
    url: "https://fatboxog.onrender.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"